# jaliRNA Docker Compose - Para desenvolvimento local
version: '3.8'

services:
  jalirna-api:
    build: .
    ports:
      - "5001:8000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped